---
abstract: 'Yet another distribution maker'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>'
build_requires:
  Any::Moose: 0
  ExtUtils::MakeMaker: 6.42
  Moose: 0
  MooseX::StrictConstructor: 0
  Test::Perl::Critic: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Dist::Maker
name: Dist-Maker
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  Config::Tiny: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 0
  Getopt::Long: 2.36
  Module::Install: 0
  Module::Install::AuthorTests: 0
  Module::Install::Repository: 0
  Module::Install::XSUtil: 0
  Mouse: 0.64
  MouseX::NativeTraits: 0.002
  MouseX::StrictConstructor: 0.02
  Test::LeakTrace: 0.13
  Test::More: 0.88
  Test::Requires: 0.03
  Text::Xslate: 0.2008
  parent: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/Dist-Maker.git
version: 0.02
